name: linux

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        build_type: [debug, release, distribution]
      fail-fast: false

    steps:
    - name: Update dependencies
      run: sudo apt update

    - name: Install Open GL
      run: sudo apt install libgl1-mesa-dev

    - name: Install Vulkan
      run: sudo apt install libvulkan1 libvulkan-dev

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create build directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGG_CORE=ON -DGG_APP=ON -DGG_APP_WINDOW_SUPPORT=ON -DGG_CONFIG=ON -DGG_LOG=ON -DGG_GFX=ON -DGG_GFX_OPENGL_SUPPORT=ON -DGG_GFX_VULKAN_SUPPORT=ON -DGG_GUI=ON -DGG_LIBS_ENABLE_TESTING=ON

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure
